- name: "create vm"
  shell: |
    yc compute instance create \ 
    --name {{ vm_name }} \ 
    --cores {{ vm_cores }} \ 
    --memory {{ vm_mem }} \ 
    --create-boot-disk size={{ vm_boot_disk_size }},image-folder-id=standard-images,image-family={{ vm_image }} \
    --public-ip \
    --"metadata": {
  "user-data": "#cloud-config\nusers:\n  - name: iadmin\n    groups: sudo\n    shell: /bin/bash\n    sudo: ['ALL=(ALL) NOPASSWD:ALL']\n    ssh-authorized-keys:\n      - ssh-dss AAAAB3NzaC1kc3MAAACBAIQc4j+TcuKmL7jYZXuNNBqoEcc+qnEApN4y+23hH40xCvxfj2hKLZ5Q/SmC4nJW2YMOkocF4gJFoEuIXsIew7OYEqlSDixQX3JQmgRi5LPYqz5HpEf4oJG/HZrLAJVw153CxNUmBvxxOmb2JovNdAFeVJLTxdDxvjGaV4ehZTOpAAAAFQCkNrIjD50BYuRsla1Iz4qZwyR2DwAAAIAdcgjXD2rBLKTkVANWJpElYkytrVuaDhj1dc+8Xhry0ogfVf1StVuLmNfkVcTQ8/84V7lN/MO/JFW2awHaLGnvYyUuXRB0VdsIjXLZni0vxdZUg5yH6yjbq3ErwghoLJV4FBq3AF92OqW1cvgFU1e/MHfjCazw1gKfr0qwJ///MgAAAIBWeowAScrpc4hdPV1b1BzkAn1/8govol/OQwogQX45UU4N7NLllGyNbmYzjS4QeAxbHtY9SeQ8zjafrbYXI0kr5dz2OcMX+1Mpqqqo8NbbtM/riNOF8dW1c02msX8shHlddV2X3QhXLv3r3s/QCtXQwVEIJr4LHYaOX/QvIZR6Xg=="
}